[profile.default]
src = "src"
out = "out"
libs = ["dependencies", "lib"]
solc = "0.8.23"
evm_version = "paris"
optimizer = true
optimizer_runs = 1000000
remappings = ["forge-std-1.10.0/=dependencies/forge-std-1.10.0/"]

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = true
remappings_prefix = ""
remappings_location = "config"
recursive_deps = false

[dependencies]
forge-std = "1.10.0"
"@openzeppelin-contracts" = "5.1.0"
"@1inch-solidity-utils" = "5.0.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
